### ISSUE TITLE
LSIDs cause broken links

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/checklistbank#798] opened 2021-01-20 16:35 UTC
WoRMS is using LSIDs as their IDs, which causes problems because of the colons. In particular, the LSID links on the verbatim page are broken:

https://data.catalogueoflife.org/dataset/2251/verbatim?issue=chained%20basionym

I could discourage them from using LSIDs and suggest that they just use the numeric part of the ID because I expect that it might cause issues for some browsers, although this URL works fine for Firefox and Chrome:

https://data.catalogueoflife.org/dataset/2251/name/urn:lsid:marinespecies.org:taxname:1252865

Other people might try to use LSIDs as well though.

**Comment by mdoering** [comment] 2021-01-20 16:45
The same problem will arise with any URIs which are popular for GUIDs. 
So we need to make sure any URI as an ID works just fine, in particular [colons in the path](https://stackoverflow.com/questions/1737575/are-colons-allowed-in-urls).

The fact that the LSIDs are converted to links does not seem bad. They 
What are the actual open issues?
 - LSID URNs converted to html links? @thomasstjerne is this some automated marking up? These links don't work without an resolver, but it's also not too bad to have such dead links
 - The cross link symbol is missing to use the LSID as a search parameter. This needs fixing, maybe it is the cause of the active LSID above?
 - LSID as application path params seem to be working just fine. Otherwise this is an apache config problem I suspect.

**Comment by gdower** [comment] 2021-01-20 17:12
Maybe it is just a bad link in ChecklistBank? The HTML code is:

```
<a href="urn:lsid:marinespecies.org:taxname:1252865" target="_blank">urn:lsid:marinespecies.org:taxname:1252865</a>
```

So it's missing the full URL.

**Comment by bart-v** [comment] 2021-01-20 22:31
WoRMS will stick with LSIDs, they have been our GUID/PID choice since the start, they are real P(ermanent)IDs!

This specific issue (non working links) can easily be fixed by just prefixing the href with "http://www.lsid.info/" so it becomes

`<a href="http://www.lsid.info/urn:lsid:marinespecies.org:taxname:1252865" target="_blank">urn:lsid:marinespecies.org:taxname:1252865</a>`

**Comment by mdoering** [comment] 2021-01-21 04:28
Thanks @bart-v. I think the link shown is actually the bug. There should not have been a link for the LSID, but instead a link to the application with the LSID as a parameter. @thomasstjerne can you confirm?

**Closed** 2021-01-21 07:54 UTC

**Comment by thomasstjerne** [comment] 2021-01-21 07:57
No, its a regex for urls used to make links if a value in the verbatim data looks like an URI. And it caught the LSID, but now i link to the LSID resolver if it is an LSID

**Comment by mdoering** [comment] 2021-01-21 14:22
And also show the anchor link to search for related records by ID?

**Comment by mdoering** [comment] 2021-01-21 14:36
The interlinking seems wrong still.
All foreign keys should point to the record with the primary key, primary keys to the list of records that contain a foreign key to there.

In the Neuropterida dataset referenceID, nameID and parentID become links to the primary record:

<img width="587" alt="Screenshot 2021-01-21 at 15 25 11" src="https://user-images.githubusercontent.com/327505/105364864-ef070400-5bfd-11eb-9870-db1d608359f0.png">

In the Mollusca example this is not the case:

<img width="755" alt="Screenshot 2021-01-21 at 15 33 26" src="https://user-images.githubusercontent.com/327505/105365086-2aa1ce00-5bfe-11eb-84b0-9962f3ef1734.png">

Some other IDs are missing in both cases:
 - Name.referenceID 
 - Name.basionymID

**Comment by mdoering** [comment] 2021-01-21 14:39
terms.json, found it. Im fixing this

**Comment by mdoering** [comment] 2021-01-21 14:55
just leaves the LSID crosslinks
