### ISSUE TITLE
Running imports not showing in the import queue

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/checklistbank#1091] opened 2022-08-31 15:59 UTC
Here's more info on the issue with running imports not displaying the queue that I mentioned in the stand-up. It looks like this:

![image](https://user-images.githubusercontent.com/8573609/187722515-c6fb38cf-379f-4f65-9980-a722bf38dbf4.png)

I only see the frontend repeatedly calling:

GET https://www.checklistbank.org/imports?limit=10&offset=0&state=unchanged&state=finished&state=canceled&state=failed

I suspect it has something to do with URL params with the imports link redirecting to this [URL](https://www.checklistbank.org/imports?limit=10&offset=0&state=unchanged&state=finished&state=canceled&state=failed). If I [manually change the URL](https://www.checklistbank.org/imports?limit=10&offset=0&state=processing) parameters processing jobs do show:

![image](https://user-images.githubusercontent.com/8573609/187722879-4591dd3e-cfd7-4af6-a75b-104c90dbdb93.png)

I think this will be a nice enhancement, so thanks for implementing it, @thomasstjerne!

**Comment by thomasstjerne** [comment] 2022-09-01 08:51
Thanks @gdower 
I _think_ I´ve got it now, buut I´ll leave the issue open until we can confirm it works

**Comment by gdower** [comment] 2023-02-15 16:34
There's still a similar issue with the imports queue. To reproduce:

1) Navigate to here: https://www.checklistbank.org/imports
2) The import queues will load correctly
3) View the URL after it loads and it will be: https://www.checklistbank.org/imports?limit=10&offset=0&state=unchanged&state=finished&state=canceled&state=failed
4) Hit the refresh button and it loads the finished datasets into the running queue because of the URL state params affect the running queue:

<img width="1918" alt="image" src="https://user-images.githubusercontent.com/8573609/219091251-fbe48896-aa36-4af3-bf36-75b915ba4b68.png">

Ideally if you can prevent the state parameters from loading into the URL, it will fix the issue.

**Comment by mdoering** [comment] 2023-02-15 16:59
Duplicate of https://github.com/CatalogueOfLife/checklistbank/issues/1156?

**Closed** 2023-02-15 17:02 UTC
