### ISSUE TITLE
Search names across all datasets

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#528] opened 2020-04-01 08:51 UTC
How can I search across all datasets in the Clearinghouse for a specific name?

We should open up the search to all datasets with the dataset filter being optional and also allowed to take a list of values, i.e. to search across a selected list of datasets only.

Another way to look for a name across all datasets is to go through the names index.
This is preferable for whole names, but does not allow all the search options.

**Comment by thomasstjerne** [comment] 2020-04-16 12:19
Duplicate of https://github.com/CatalogueOfLife/clearinghouse-ui/issues/529 ?

**Comment by mdoering** [comment] 2020-04-16 14:58
Could be a duplicate, but exposing the names index is slightly different from searching for usages across all datasets. It's like we allow in GBIF in the advanced species search. Basically a regular names search but only optionally limited by a dataset or a selection of them. The search API already allows for this. You also get facets back for searches across all datasets, the names index is slightly different

**Closed** 2022-03-08 13:14 UTC
