### ISSUE TITLE
Checklistbank on PROD paralyzed?

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/checklistbank#976] opened 2021-12-03 13:57 UTC
@mdoering (@gdower) 

It looks like the checklistbank on prod is paralyzed. 

30 checklists with stuck import:
![image](https://user-images.githubusercontent.com/28574252/144614179-d4de2e7d-ea5d-42a5-9ef1-6f44124cc215.png)

161 sectors are waiting syncs (no changes since yesterday):
![image](https://user-images.githubusercontent.com/28574252/144613469-99f9b788-5702-4e62-b92b-6535da0028de.png)

**Comment by yroskov** [comment] 2021-12-03 14:02
Already reported here: https://github.com/CatalogueOfLife/backend/issues/1079

**Comment by mdoering** [comment] 2021-12-03 15:31
closing because its a duplicate of CatalogueOfLife/backend#1079
Sth is seriously wrong, but I don't know what. The syncs are likely ghosts and dont really exist so they are not waiting.
Would it be easy to request them to be synced again?

The imports are really slow lately, no idea why that is

**Closed by mdoering** 2021-12-03 15:31 UTC
