### ISSUE TITLE
Workbench link not showing source and decision options

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#1313] opened 2023-11-13 10:11 UTC
https://www.checklistbank.org/catalogue/3/dataset/1166/workbench?decisionMode=_NULL&facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=500&offset=0&q=%5BGENUS%20NOT%20SPECIFIED%5D

The source menu does not appear to be loaded correctly when you enter application with the link above.
And there is no option to leave decisions for some reason although I am admin:

<img width="1771" alt="image" src="https://github.com/CatalogueOfLife/checklistbank/assets/327505/80879d91-9791-4174-a0fc-eb95af7e9c4e">

**Comment by mdoering** [comment] 2023-11-13 10:11
see also https://github.com/CatalogueOfLife/checklistbank/issues/1310

**Comment by thomasstjerne** [comment] 2023-11-16 09:28
I am not able to reproduce this. Can you try clicking the link above again and see if you can reproduce it?

**Comment by mdoering** [comment] 2023-11-16 09:42
Yes I can:
<img width="1596" alt="image" src="https://github.com/CatalogueOfLife/checklistbank/assets/327505/13192972-a9dd-4a47-aa05-dfd5c4214c6d">

Maybe its a Safari thing?

**Comment by mdoering** [comment] 2023-11-16 09:50
same on Chrome: 
<img width="1718" alt="image" src="https://github.com/CatalogueOfLife/checklistbank/assets/327505/7d971a09-6f00-41a2-8bed-2c83db73979f">

**Comment by thomasstjerne** [comment] 2023-11-16 11:54
I have re-written the source selector. I think this solves the source menu issue.
However, the decision option not showing is probably something else

**Comment by mdoering** [comment] 2023-11-17 09:35
Source shows perfectly now!

**Comment by thomasstjerne** [comment] 2023-11-17 09:45
But still no access to decisions?

**Comment by mdoering** [comment] 2023-11-28 09:34
I still cannot add any decision in the workbench for my projects.

**Comment by mdoering** [comment] 2024-02-12 13:06
I still cannot apply any decisions

**Comment by thomasstjerne** [comment] 2024-02-12 13:24
Please see if this is also still the case on dev? Prod is quite far behind on deployments

**Comment by mdoering** [comment] 2024-02-12 16:22
indeed works on DEV. We need to get prod up to date asap!

**Comment by thomasstjerne** [comment] 2024-02-15 12:34
Closing this, as it is fixed in code then.

**Closed by thomasstjerne** 2024-02-15 12:34 UTC
Labels: bug, high priority
