### ISSUE TITLE
I am unable to view/edit GSD metadata inside the project

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/checklistbank#867] opened 2021-05-13 21:14 UTC
I need to setup a patch for WoRMS Nematoda GSD, id 2302 on prod:
https://data.catalogueoflife.org/catalogue/3/dataset/2302/about

Frontend version: a65157e May 12, 2021 10:02 AMBackend version: 3e495b2 May 12, 2021 1:46 PM

When I chosen menu item "About", I have got an error message 404. 

![image](https://user-images.githubusercontent.com/28574252/118188288-c0f43c80-b405-11eb-8d95-4047d2ef1af3.png)

@mdoering @thomasstjerne

**Comment by mdoering** [comment] 2021-05-13 23:02
yes. As a immediate workaround please manually change the URL from /about to /meta

**Comment by mdoering** [comment] 2021-05-13 23:03
duplicate of https://github.com/CatalogueOfLife/checklistbank/issues/866

**Closed** 2021-05-14 07:15 UTC
Labels: bug
