### ISSUE TITLE
GBIF impact tool -  Results that don't reflect the actual COL/XCOL impact

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/checklistbank#1470] opened 2024-09-25 21:49 UTC
Some examples of this issue in name with high impact in occurrences

[Anas platyrhynchos Linnaeus, 1758](https://www.checklistbank.org/dataset/303167/taxon/DGP6) is part of COL so it shouldn't be flagged by the GBIF impact tool as an "interpretation change"

<img width="964" alt="Captura de pantalla 2024-09-25 a la(s) 1 57 28 p m" src="https://github.com/user-attachments/assets/fdf3c886-cb55-43a2-8527-f6b8c8e6ee30">

Same with [Streptopelia capicola (Sundevall, 1857)](https://www.checklistbank.org/dataset/303167/taxon/6ZXQ2)

<img width="789" alt="Captura de pantalla 2024-09-25 a la(s) 4 39 51 p m" src="https://github.com/user-attachments/assets/7f337497-80f9-44cd-898e-2a95243878ae">

Same with [Lamprotornis nitens (Linnaeus, 1766)](https://www.checklistbank.org/dataset/303429/taxon/3S5QW)

<img width="829" alt="Captura de pantalla 2024-09-25 a la(s) 4 47 52 p m" src="https://github.com/user-attachments/assets/bb7bed54-721e-4f89-89cb-06557e251c08">

Same with  [Ardea intermedia Wagler, 1829](https://www.checklistbank.org/dataset/303167/nameusage/CLD6T)

<img width="752" alt="Captura de pantalla 2024-09-25 a la(s) 3 30 04 p m" src="https://github.com/user-attachments/assets/ee47be63-a026-4cca-bb75-42d673dc59ee">

**Comment by mdoering** [comment] 2024-09-30 12:27
[Anas platyrhynchos exists twice](https://www.checklistbank.org/dataset/303772/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nomCode&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&facet=sectorMode&facet=secondarySourceGroup&facet=sectorDatasetKey&facet=group&limit=50&nameType=scientific&offset=0&q=Anas%20platyrhynchos&rank=species),  once as a canonical version. Guess the problem is linked to that.

**Comment by camiplata** [comment] 2024-09-30 18:15
@mdoering did you already remove the Azores list? I was doing it but i cannot find it

**Comment by mdoering** [comment] 2024-09-30 19:37
No. I only started work for a new enforceUnique config that makes sure a name only gets accepted once

**Comment by mdoering** [comment] 2024-10-01 07:31
Some matching problems were due to a bug in the query parameter consumption of the matching service if the name was given only atomized with `genus=Streptopelia&specificEpithet=capicola`. Fixed in https://github.com/CatalogueOfLife/checklistbank/commit/1345830eebba1c4e712ec3e849278cb3a5cac853

**Closed** 2024-10-01 07:42 UTC
